### ISSUE TITLE
做成電子報

### ISSUE THREAD

**Issue by tigercosmos** [WeiChiaChang/Weekly-GitHub-Digest#1]
信箱直接收，像碼天狗、TechBridge那樣

**Comment by WeiChiaChang** [comment]
@tigercosmos 謝謝你的關注和建議 ～
不好意思最近公司太忙有點晚回覆＠＠
之前有看過你寫的 [開源社群相關文章](https://medium.com/@tigercosmos/how-i-how-a-newbie-to-become-a-member-of-open-source-community-67da54c02e01) 非常受用 👍 

碼天狗和 TechBridge 兩個都很棒，我都有在 follow 哈哈
是有考慮過做成類似那樣的形式
後來想想還是讓整個 Weekly-Github-Digest 本身
就專注在 Github 這個平台經營
也因為 `watch` 本身也有類似通知的功能了
一有更新就會寄信到使用者的信箱
所以目前的打算應該會維持現狀 
但未來不排斥用像你說的方式運作～

**Comment by tigercosmos** [comment]
@WeiChiaChang  直接 Watch 會連 issue 一起通知，有點困擾

**Comment by WeiChiaChang** [comment]
@tigercosmos  謝謝你的關注以及建議 🙏，這個的確是會造成困擾的問題ＱＱ

不過由於筆者最近公司過於忙碌 Orz，這部分會認真找個空閒時間改善，也會開始朝你所說的方向做調整，Thanks a lot！

**Comment by WeiChiaChang** [comment]
@tigercosmos  你好，在反覆考慮了幾個方案的情況之下，我最後決定把 Weekly-GitHub-Digest 搬家到 [Medium](https://medium.com/weekly-github-digest) 平台，關於一些考量我是參考[這篇文章](https://larrylu.blog/migrate-from-jekyll-to-medium-b792049f0c60)的，昨天花了點時間已經把目前有的文章都搬過去了，但 GitHub 這裡我還是會持續更新，因為也有些朋友跟我反映就是只想在 GitHub 上不想刻意留信箱之類的，所以我會比較建議你把現在 GitHub 的 repo 取消 `watch`，然後到 [Medium](https://medium.com/weekly-github-digest) 平台點選 `Follow` 之後只要 Weekly-GitHub-Digest 一有更新就會收到最新一期了！我想這個方式應該會比較符合你的閱讀需求，很感謝你主動且踴躍提供的建議 👍 ，之後也會繼續努力把每期內容品質提高的。

**Comment by Larry850806** [comment]
@WeiChiaChang  謝謝你參考我的文章XD，我一直都有在 follow 你的 Weekly-Github-Digest，也希望他越來越好，加油

**Comment by tigercosmos** [comment]
@WeiChiaChang 放到 Medium 感覺很不錯！
