### ISSUE TITLE
有考虑弄成邮件推送吗？

### ISSUE THREAD

**Issue by 1c7** [WeiChiaChang/Weekly-GitHub-Digest#5]
懒。不想每次回想起来有这么一件事然后跑来这个 Github repo 去点新出的周刊。
MailChimp 或者其他的服务商，免费版的套餐应该能应对现在的需求吧？

:) 祝越做越好。

**Comment by tigercosmos** [comment]
的確蠻多服務商有在做這件事

**Comment by SSARCandy** [comment]
可以考慮改用 gitbook ?

**Comment by WeiChiaChang** [comment]
@1c7 你好～ 不好意思這陣子比較忙碌，週末才比較有時間可以回覆 @@

就像你說的 Mailchimp 和 @tigercosmos 提及的一樣，Mailchimp 和很多服務廠商都有提供類似的機制，研究過相關文件發現其實也不難實作，而 @SSARCandy 說的 GitBook 其實也蠻讚的，但在幾種不同的方案斟酌之下我最後還是選擇了 [Medium](https://medium.com/weekly-github-digest) 平台，深入細節我是參考[這篇文章](https://larrylu.blog/migrate-from-jekyll-to-medium-b792049f0c60)的，也推薦你們花些時間閱讀一下。

然後昨天花了點時間已經把目前有的文章都搬過去了，但 GitHub 這裡我還是會持續做更新，因為也有些朋友跟我反映就是只想在 GitHub 上閱讀而不想刻意留下信箱之類的，所以其實兩種需求都出現了，未來想在 GitHub 瀏覽的朋友一樣可以繼續閱讀，想透過 Medium 訂閱收到最新一期的一樣可以，在我能力範圍之內都會一併提供。相關討論串可以參考 #1 和 #4 。

真的很謝謝你們的建議和時間，開源社群真的太有愛了哈哈。

**Comment by 1c7** [comment]
好棒~ 那我 close issue 了~
