### ISSUE TITLE
[建議] 不要用斜體

### ISSUE THREAD

**Issue by tigercosmos** [WeiChiaChang/Weekly-GitHub-Digest#7]
我現在都改在 medium 上看，不過斜體數量這麼多真的不是很好閱讀。
希望大部分描述都可以用正常字體就好。

**Comment by WeiChiaChang** [comment]
你好 @tigercosmos ，謝謝你的建議，最近也在拜讀你在鐵人賽撰寫的[瀏覽器相關文章](https://ithelp.ithome.com.tw/users/20103745/ironman/1270)，非常受用  👍 

Medium 我後來也發現中文蠻多限制的，像是不能選字型等等還有像你說的斜體有點醜 Orz 
之後會做這項調整，Thanks!

**Comment by tigercosmos** [comment]
Thanks  XD
feel free to close this when you like.
